site_name: 5th Edition SRD
copyright: Provided by Wizards of the Coast under the OGL 1.0a.
site_description: A web-based version of the 5th Edition Dungeons and Dragons SRD (System Reference Document)
theme_dir: 5thsrd_theme
site_dir: 5thsrd_offline
use_directory_urls: false
plugins: []
extra:
   enable_ads: no
